config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#home'

  ## Dynamic omniauth provider eg google, facebook, github.
  ## Coming back route
  get '/auth/:provider/callback', to: 'sessions#omniauth'


  ## Nested routes for Jobs
  ## Include some custom routes that go to customer controller methods, which in turn invoke scope methods
  ## Added dynamic category param which then passes the category type into the Job.is_category scope method
  resources :jobs do
    collection do
      get 'most_popular', to: 'jobs#popular'
      get ':category', to: 'jobs#category', as: 'category'
    end
  end
  
  resources :users do
    resources :jobs
  end

  resources :jobs do
    resources :bids
  end

  resources :posters do
    resources :ratings
  end

  resources :jobs, :sessions
  get '/users/:id', to: 'users#show'
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/edit', to: 'users#edit'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :bidder
  belongs_to :job

  validates :bid_amount, presence: true
  validates :comment, presence: true

  ##
  ## Find and show bids related to the job
  ##
  def self.show_related_bids_only(job)
    @bids = Bid.all.select { |bid| bid.job_id == job.id }
  end

  def self.show_results
    Bid.all
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def new
    @bid = Bid.new
    @job = Job.find_by(id: params[:job_id])
  end

  def create
    ## Initialise variables below to create bid, find job ID, userID from sessions and bidder ID. 
    @bid = Bid.new(job_params)
    @job = Job.find_by(id: params[:job_id])
    @user = User.find_by_id(session[:user_id])
    @bidder = Bidder.find_or_create_by(user_id: @user.id)
    
    ## Set bid job_id and bid bidder_id
    @bid.job_id = @job.id
    @bid.bidder_id = @bidder.id

    ## Save and redirect /user/id/jobs/id page
    if @bid.save
      redirect_to user_job_path(@user.id, @job.id)
    else
      puts 'Borked'
      flash[:message] = @bid.errors.full_messages
      render :new
    end
  end

  def show
    @bid = Bid.find_by(id: params[:job_id])
  end

  def index
    @bids = Bid.all
  end

  private

  def job_params
    params.require(:bid).permit(:bid_amount, :comment, :bidder_id, :job_id)
  end
end

app/views/bids/_bids.html.erb
<ol>
  <% @bids.each do | bid |%>
    <li>
      <div><b><h3><%=link_to job_bidder(bid).username.capitalize, user_path(job_bidder(bid).id)%> bid $<%=bid.bid_amount%></b></h3><%=bid.comment%> </div>
      <br>
    </li>
  <%end%>
</ol>

app/views/bids/_form.html.erb
<%=flash[:message]%>
<%= bootstrap_form_for bid, url: job_bids_path do |f| %>
  <br>
  <div class="fields_with_errors"><%= f.number_field :bid_amount %> </div>
  <div class="fields_with_errors"><%= f.text_area :comment %></div>
  <br>
  <%= f.submit "Place bid" %>
<% end %>

app/views/bids/new.html.erb
<h1>Bid on job</h1>
<div>
  <span><%=link_to "Dashboard", root_path%></span> |
  <%=link_to "View Job", user_job_path(@job.poster_id, @job.id)%>
</div>
<hr>
<%= render partial: 'form', locals: {bid: @bid} %>