config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#home'

  ## Dynamic omniauth provider eg google, facebook, github.
  ## Coming back route
  get '/auth/:provider/callback', to: 'sessions#omniauth'


  ## Nested routes for Jobs
  ## Include some custom routes that go to customer controller methods, which in turn invoke scope methods
  ## Added dynamic category param which then passes the category type into the Job.is_category scope method
  resources :jobs do
    collection do
      get 'most_popular', to: 'jobs#popular'
      get ':category', to: 'jobs#category', as: 'category'
    end
  end
  
  resources :users do
    resources :jobs
  end

  resources :jobs do
    resources :bids
  end

  resources :posters do
    resources :ratings
  end

  resources :jobs, :sessions
  get '/users/:id', to: 'users#show'
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/edit', to: 'users#edit'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :poster

  has_many :bids
  has_many :bidders, through: :bids

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :day, presence: true
  validates :time, presence: true
  validates :category, presence: true

  scope :is_category, ->(category) { where(category: category) }

  ## Query most recent job posts and trim number
  scope :most_recent, -> { order('created_at desc').limit(10) }

  ## Scope method to find most popular jobs based on number of bids
  ## Join with bid table using jobs id, order and group by number of duplicate job_id
  scope :most_popular, -> { left_joins(:bids).group('jobs.id').order('count(bids.job_id) desc').limit(10) }


  def self.search(params)
    ## Search database for titles that are similar to searched value
    where('LOWER(title) LIKE ?', "%#{params}%")
  end

  ## Class method to find most popular jobs based on number of bids
  ##
  # def self.most_popular(array)
  #   results = []
  #   array.select do |bid|
  #     Job.all.select do |job|
  #       results << job if job.id == bid.job_id
  #     end
  #   end
  #   results
  # end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = if params[:user_id]
              User.find(params[:user_id]).jobs
            elsif params[:q]
              ## If search param exists, pass search argument into Job object and invoke search class method
              Job.search(params[:q].downcase)
            else
              ## No filter applied
              Job.all
            end
  end

  def show
    ## Check and see if job id is valid otherwise redirect to homepage
    @job = Job.find_by(id: params[:id]) || redirect_to(root_path)
    @bids = Bid.show_related_bids_only(@job)
  end

  def new
    @job = Job.new
    @user = User.find_by(id: params[:user_id])
    @url = user_jobs_path
  end

  def create
    ## Initialise variables below for user, poster by finding or creating, creating new Job and url helper which we pass into our partial so we can use same partial for edit and new
    # @url = user_jobs_path

    # @user = User.find_by(id: params[:user_id])
    @poster = Poster.find_or_create_by(user_id: current_user.id)
    @job = Job.new(job_params)

    ## Set Job Poster_id to Poster.id
    ## Job belongs to Poster
    @job.poster_id = @poster.id

    ## If Job saves, redirect to users/id/job
    if @job.save
      redirect_to user_job_path(@poster.user_id, @job.id)
    else
      flash[:message] = @job.errors.full_messages
      render :new, notice: @message
    end
  end

  def popular
    ## Scope method for most popular Jobs. This is based on how many bids so probably not really "most popular"
    @jobs = Job.most_popular
  end

  def category
    ## Scope method to find all items in table that match category name
    ## category param is passed into scope method when this customer Jobs controller method is called
    @jobs = Job.is_category(params[:category])
  end

  def edit
    ## Initialise variable for URL helper which we pass to forms partial
    @job = Job.find_by(id: params[:id])
    @url = user_job_path
  end

  def update


    # @user = User.find_by(id: params[:user_id])
    @job = Job.find_by(id: params[:id])
    @poster = Poster.find_by(user_id: current_user.id)

    ## If job updates redirect to user/id/jobs/id to view job
    if @job.update(job_params)
      redirect_to user_job_path(@poster.user_id, @job.id)
    else
      @message = 'Your details are incorrect. Please try again.'
      render :edit, notice: @message
    end
  end

  # def destroy
  #   @job = Job.find_by(params[:id])
  #   @job.delete
  #   redirect_to user_path
  # end

  private

  def job_params
    params.require(:job).permit(:title, :category, :description, :price, :day, :time, :poster_id)
  end
end

app/views/jobs/_form.html.erb
<div class="fields_with_errors">
<%= form_for job do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% job.errors.each do |error| %>
          <li style="color:red;"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="fields_with_errors"><%= f.text_field :title %></div>
  <br>
  <div class="fields_with_errors"><%= f.select :category, options_for_select([ "Wash & groom", "Walk & exercise", "Overnight stay", "Training", "Other"]), :class => 'genForm_dropBox' %></div>
  <br>
  <div class="fields_with_errors"><%= f.text_area :description %></div>
  <br>
  <div class="fields_with_errors"><%= f.text_field :price %></div>
  <br>
  <div class="fields_with_errors"><%= f.select :day, options_for_select([ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]), :class => 'genForm_dropBox' %></div>
  <br>
  <div class="fields_with_errors"><%= f.select :time, options_for_select([ "Morning", "Afternoon", "Evening"]), :class => 'genForm_dropBox' %></div>
  <br>
  <%= f.submit "Post job" %>
<% end %>
</div>

app/views/jobs/_jobs.html.erb
<% jobs.each do | job |%>
  <li>
    <div><b>
        <h3><%=link_to job.title, user_job_path(job_poster(job).id, job.id)%></b></h3>
      <h4>- <%=job_poster(job).username.capitalize%> will pay $<%=job.price%></h4>
    </div>
  </li>
<%end%>

app/views/jobs/category.html.erb
<h1><%=@jobs[0].category%></h1>
<div>
<span><%=link_to "Dashboard", root_path%></span> |
<span><%=link_to "View all jobs", jobs_path%></span>
</div>
<hr>
<%= render partial: 'jobs', locals: {jobs: @jobs} %>

app/views/jobs/edit.html.erb
<h1>Edit job</h1>
<div>
<span><%=link_to "Dashboard", root_path%></span> |
<%= link_to "My profile", user_path(current_user)%>
</div>
<hr>
<%= render partial: 'form', locals: {job: @job} %>

app/views/jobs/index.html.erb
<h1>All jobs</h1>
<div>
  <span><%=link_to "Profile", user_path(current_user.id)%></span> | 
  <span><%=link_to "Post a Job", new_user_job_path(current_user.id)%></span> |
  <span><%=link_to "Dashboard", root_path%></span>
</div>
<hr>
<div>
  <h4>Search</h4>
  <%= form_tag("/jobs", method: "get") do %>
    <%= text_field_tag(:q) %>
    <%= submit_tag "Search" %>
  <% end %>
  <br>
  <span><%=link_to "Clear search", jobs_path%></span> | 
  <span><%=link_to "Most popular", most_popular_jobs_path%></span> | 
  <span><%=link_to "Wash & groom", category_jobs_path("Wash & groom")%></span> | 
  <span><%=link_to "Walk & exercise", category_jobs_path("Walk & exercise")%></span> | 
  <span><%=link_to "Overnight stay", category_jobs_path("Overnight stay")%></span> | 
  <span><%=link_to "Training", category_jobs_path("Training")%></span>
</div>
<%= render partial: 'jobs', locals: {jobs: @jobs} %>

app/views/jobs/new.html.erb
<h1>Create job</h1>
<div>
<span><%=link_to "Dashboard", root_path%></span>
</div>
<hr>
<%= render partial: 'form', locals: {job: @job} %>

app/views/jobs/popular.html.erb
<h1>Most popular</h1>
<div>
<span><%=link_to "Dashboard", root_path%></span> |
<span><%=link_to "View all jobs", jobs_path%></span>
</div>
<hr>
<%= render partial: 'jobs', locals: {jobs: @jobs} %>

app/views/jobs/show.html.erb
<br>
<p> <%=@job.category%> </p>
<h1><%=@job.title%></h1>
<div>
  <% if current_user.id == job_poster(@job).id %>
    <%=link_to "Update job", edit_user_job_path(job_poster(@job).id, @job.id)%> |
    <%=link_to "Back to profile", user_path(job_poster(@job).id)%>
  <%else%>
    <%=link_to "Bid on job", new_job_bid_path(@job.id)%> |
    <%=link_to "View poster", user_path(job_poster(@job).id)%> |
    <%=link_to "Dashboard", root_path%>
  <%end%>
</div>
<hr>
<p> <%=@job.description%> </p>
<p> <%=@job.day%> - <%=@job.time%> </p>
<hr>
<h2>$<%=@job.price%></h2>
<hr>
<h2>Bids</h2>
<%= render partial: 'bids/bids', locals: {bids: @bids} %>