config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#home'

  ## Dynamic omniauth provider eg google, facebook, github.
  ## Coming back route
  get '/auth/:provider/callback', to: 'sessions#omniauth'


  ## Nested routes for Jobs
  ## Include some custom routes that go to customer controller methods, which in turn invoke scope methods
  ## Added dynamic category param which then passes the category type into the Job.is_category scope method
  resources :jobs do
    collection do
      get 'most_popular', to: 'jobs#popular'
      get ':category', to: 'jobs#category', as: 'category'
    end
  end
  
  resources :users do
    resources :jobs
  end

  resources :jobs do
    resources :bids
  end

  resources :posters do
    resources :ratings
  end

  resources :jobs, :sessions
  get '/users/:id', to: 'users#show'
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/edit', to: 'users#edit'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :bidder
  has_one :poster

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, length: { minimum: 10, maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password

  def show_jobs
    jobs
  end

  def self.create_from_omniauth(auth)
    User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
      u.username = auth['info']['first_name']
      u.email = auth['info']['email']
      u.password = SecureRandom.hex(24)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new

  end

  def create

    ## Initialise user by creating new user and passing in user_params method
    @user = User.new(user_params)
    
    ## If user saves, set session id to user id and direct customer to home page
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: @user
    else
      @message = 'Your details are incorrect. Please try again.'
      render :new, notice: @message
    end
  end

  def show
    ## Initilise variables for user and poster so we can show them on profile page
    @user = User.find_by(id: params[:id])
    @poster = Poster.find_by(user_id: params[:id]) ? Poster.find_by(user_id: params[:id]) : nil 
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find_by(id: params[:id])
    @url = user_path
  end

  def update
    @url = user_path
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      @message = 'Your details are incorrect. Please try again.'
      render :edit, notice: @message
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<%= bootstrap_form_for user, url: url do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% user.errors.each do |error| %>
          <li style="color:red;"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div><%= f.text_field :username %></div>
  <br>
  <div><%= f.text_field :email %></div>
  <br>
  <div><%= f.password_field :password %></div>
  <br>
  <div><%= f.password_field :password_confirmation %></div>
  <br>
  <%= f.submit "Update" %>
<% end %>

app/views/users/edit.html.erb
<h1>Update <%=@user.username.pluralize.capitalize%> profile</h1>
<%= render partial: 'form', locals: {user: @user, url: @url} %>
<br>
<%=link_to "My profile", user_path%>

app/views/users/index.html.erb
<ul>
  <% @users.each do | user |%>
    <li>
      <%=user.username%> - <%=user.email%>
    </li>
  <%end%>
</ul>

app/views/users/new.html.erb
<h1>Sign up to Pet Tasker</h1>
<%= bootstrap_form_for :user, url: '/signup' do |f| %>
  <div style="color:red;">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </div>
  <div><%= f.text_field :username %></div>
  <div><%= f.text_field :email %></div>
  <div><%= f.password_field :password %></div>
  <div><%= f.password_field :password_confirmation %></div>
  <%= f.submit "Sign up" %>
<% end %>
<br>
<%=button_to "Login with Google", '/auth/google_oauth2'%>

<%=link_to "Log in", login_path%>
<br>

app/views/users/show.html.erb
<h1><%=@user.username.pluralize.capitalize%> profile</h1>
<%=link_to "Dashboard", root_path%> |
<%=link_to "Rate Poster", new_poster_rating_path(@user.poster)%>
<% if current_user.id == @user.id %>
  | <%=link_to "Update profile", edit_user_path(@user.id)%>
  | <%=link_to "Post a job", new_user_job_path(@user)%>
<%else%>
<%end%>
<hr>
<% if current_user.id == @user.id %>
  <li>
    <div>
      <h3>Username</h3>
    </div>
    <div>
      <h4><%=@user.username.capitalize%></h4>
    </div>
  </li>
  <hr>
  <li>
    <div>
      <h3>Email</h3>
    </div>
    <div>
      <h4><%=@user.email%></h4>
    </div>
  </li>
  <hr>
  <li>
    <div>
      <h3>Password</h3>
    </div>
    <div>
      <h4>********</h4>
      <div>
      </div>
    </li>
    <hr>
  <%else%>
  <%end%>
  <h2>My jobs</h2>
  <div>
    <% if @poster%>
      <%= render partial: 'jobs/jobs', locals: {jobs: @poster.jobs}%>
    <% else%>
    <%end%>
  </div>
  <br>
  <%=button_to "Logout", logout_path%>